@startuml

skinparam linetype ortho
set namespaceSeparator none
'hide circle

package edu.monash.fit2099.engine {
    abstract class Actor <<abstract>>
    abstract class WeaponItem <<abstract>>
}

package game {

    'Enemies
    abstract class Enemy <<abstract>> #lime
    interface IEnemy <<interface>> #lime
    class HeavySkeletalSwordsman #lime
    class LoneWolf
    class GiantCrab #lime
    'Trader
    abstract class Trader <<abstract>> #lime
    interface ITrader <<interface>> #lime
    class MerchantKale #lime
    ' Things that can be picked up
    abstract class Consumables <<abstract>> #lime
    abstract class Equippable <<abstract>> #lime


    ' Driver Class
    class Application

    ' ===== Generalisations (Parent/Child) =====
    ' Trader is generalised by MerchantKale
    MerchantKale -u[#orange]-|> Trader

    ' Enemy is generalised by the enemies
    HeavySkeletalSwordsman --[#blue]-|> Enemy
    LoneWolf --[#blue]-|> Enemy
    GiantCrab --[#blue]-|> Enemy

    ' Different weapons who have a parent, WeaponItem
    Club -[#green]-|> WeaponItem
    GreatKnife --up[#green]-|> WeaponItem
    Uchigatana --up[#green]-|> WeaponItem
    Grossmesser --up[#green]-|> WeaponItem

    'Runes are Consumable
    Rune --up-|> Consumables

    'WeaponItem is Equippable
    WeaponItem --left-|> Equippable

    ' ===== Realisations (Interfaces) =====
    ' ITrader is realised by Trader
    Trader .up.|> ITrader

    ' IEnemy is realised by Enemy
    Enemy .down..|> IEnemy

    ' ===== Associations =====
    ' MerchantKale who trades weapons
    MerchantKale "1" --up[#red]-> "0..*" GreatKnife : <color:red>transacts
    MerchantKale "1" --up[#red]-> "0..*" Uchigatana : <color:red>transacts
    MerchantKale "1" --up[#red]-> "0..*" Club : <color:red>transacts
    MerchantKale "1" --up[#red]-> "0..*" Grossmesser : <color:red>transacts

    ' Enemies dropping Runes
    HeavySkeletalSwordsman --up-> "1" Rune : drops
    LoneWolf --up-> "1" Rune : drops
    GiantCrab --up-> "1" Rune : drops

    ' ===== Dependencies =====
    ' Application creates MerchantKale
    Application ..up.> MerchantKale

    ' Application creates Enemies
    Application .left..> HeavySkeletalSwordsman
    Application .left..> LoneWolf
    Application .left..> GiantCrab
}

@enduml
